const $=id=>document.getElementById(id);
const state={maps:['NUMEROLOGY'],question:'self',payload:null,analysis:null};

function goTo(id){$(id)?.scrollIntoView({behavior:'smooth',block:'start'});}
function setStep(n){document.querySelectorAll('.step').forEach(s=>s.classList.toggle('active',s.dataset.step===String(n)));}
function reset(){state.maps=['NUMEROLOGY'];state.question='self';state.payload=null;state.analysis=null;$('analysis-form').reset();$('astrology').checked=false;$('palmistry').checked=false;$('input-step').classList.remove('hidden');$('question-step').classList.add('hidden');$('reading').classList.add('hidden');setStep(1);goTo('workspace');}
$('start-reading').onclick=()=>goTo('workspace');$('closing-cta').onclick=()=>{reset();};$('new-reading').onclick=reset;$('mobile-new').onclick=()=>{reset();$('mobile-menu').classList.remove('open')};$('reset-reading').onclick=reset;$('back-data').onclick=()=>{ $('question-step').classList.add('hidden');$('input-step').classList.remove('hidden');setStep(1);goTo('workspace')};
$('menu-btn').onclick=()=>$('mobile-menu').classList.toggle('open');

document.querySelectorAll('.question-card').forEach(card=>card.onclick=()=>{document.querySelectorAll('.question-card').forEach(c=>c.classList.remove('selected'));card.classList.add('selected');state.question=card.dataset.question;$('custom-question').classList.toggle('hidden',state.question!=='custom')});

document.querySelectorAll('.map-toggle input').forEach(i=>i.onchange=()=>{if(i.id==='astrology'){i.checked?state.maps.push('ASTROLOGY'):state.maps=state.maps.filter(x=>x!=='ASTROLOGY')}if(i.id==='palmistry'){i.checked?state.maps.push('PALMISTRY'):state.maps=state.maps.filter(x=>x!=='PALMISTRY')}});

$('analysis-form').onsubmit=e=>{e.preventDefault();$('form-error').hidden=true;state.payload=collectPayload();$('input-step').classList.add('hidden');$('question-step').classList.remove('hidden');setStep(2);goTo('workspace')};
function collectPayload(){const date=$('birth_date').value||null,time=$('birth_time').value||'';return{name:$('name').value.trim()||null,birth_date:date,birth_datetime:(date&&time)?`${date}T${time}:00+05:30`:null,latitude:$('latitude').value?Number($('latitude').value):null,longitude:$('longitude').value?Number($('longitude').value):null,target:{theme_id:'TH-001',sub_theme_id:null,axis_id:'A01',semantic_level:'AXIS',temporal_scope:null,context_scope:null},requested_maps:[...new Set(state.maps)],question:state.question==='custom'?$('question').value.trim():state.question}};

const API_TOKEN=window.__THREE_MAPS_TOKEN__||'local-dev-token';
$('run-reading').onclick=async()=>{if(state.question==='custom'&&!$('question').value.trim()){alert('Please enter your question.');return}setStep(3);$('question-step').classList.add('hidden');$('reading').classList.remove('hidden');goTo('reading');renderLoading();try{const response=await fetch('/v1/analyses',{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${API_TOKEN}`,'X-Request-ID':crypto.randomUUID()},body:JSON.stringify(state.payload)});const body=await response.json();if(!response.ok)throw new Error(body.detail||'The analysis could not be completed.');const detail=await fetch(`/v1/analyses/${body.analysis_id}`,{headers:{'Authorization':`Bearer ${API_TOKEN}`}}).then(r=>r.json());state.analysis=detail;renderResult(detail)}catch(err){renderError(err.message)}};
function renderLoading(){$('reading-title').textContent='Reading the available maps…';$('reading-subtitle').textContent='Calculating structured signals and checking evidence availability.';$('relationship-state').textContent='Reading…';$('relationship-copy').textContent='The system is evaluating the selected maps.';$('fusion-score').textContent='—';$('fusion-label').textContent='CALCULATING';$('explanation-title').textContent='Evidence before interpretation.';$('explanation-copy').textContent='Please wait while the structured result is assembled.'}
function renderResult(d){const n=d.maps?.numerology;const a=d.maps?.astrology;const palm=d.maps?.palmistry;$('reading-title').textContent=questionTitle();$('reading-subtitle').textContent=`${(d.available_maps||[]).length} map(s) available · ${d.status||'COMPLETED'}`;if(n){$('num-value').textContent=n.life_path?.reduced_value??n.life_path?.value??'—';$('num-copy').textContent='Life Path · Birthday '+(n.birthday?.reduced_value??'—')}else{$('num-value').textContent='Unavailable'}if(a){$('astro-value').textContent=a.ascendant?.sign??'Chart ready';$('astro-copy').textContent=`${Object.keys(a.planets||{}).length} planetary records · sidereal`;$('astro-badge').textContent='AVAILABLE'}else{$('astro-value').textContent='Unavailable';$('astro-copy').textContent='Birth time + coordinates required';$('astro-badge').textContent='UNAVAILABLE'}if(palm){$('palm-value').textContent='Available';$('palm-badge').textContent='AVAILABLE'}const rel=d.relationship||d.results?.relationship||{};$('relationship-state').textContent=rel.state||'Single-map signal';$('relationship-copy').textContent=rel.broad_directional_convergence?'Meaningful directional convergence is present across the available evidence.':'The available evidence is qualified by map coverage and relationship conditions.';const fus=d.fusion||d.results?.fusion||{};const score=Number(fus.fusion_strength??fus.score);if(Number.isFinite(score))setFusion(score,fus.label);else setFusion(null,'NOT CALCULATED');$('confidence').textContent=pct(fus.data_confidence);$('coverage').textContent=pct(fus.coverage);$('maps-count').textContent=`${(d.available_maps||[]).length} / ${state.maps.length}`;const exp=d.explanation||d.results?.explanation||{};$('explanation-title').textContent=exp.result_statement||exp.summary||'Validated result';$('explanation-copy').textContent=exp.interpretation||exp.qualification_statement||'Interpretation remains bounded by validated evidence.';$('timing-note').textContent='TIMING: '+(exp.timing_state||'SEE TEMPORAL LAYER');$('confidence-note').textContent='DATA CONFIDENCE: '+pct(fus.data_confidence);}
function questionTitle(){return({self:'Your first pattern.',relationships:'The relationship map.',career:'Your work & direction map.',now:'What is active now?',custom:$('question').value.trim()})[state.question]||'Your three maps.'}
function setFusion(score,label){$('fusion-score').textContent=score==null?'—':score.toFixed(2);$('fusion-label').textContent=label||'FUSION STRENGTH';const ring=$('ring-value');const v=score==null?0:Math.max(0,Math.min(100,score));ring.style.strokeDashoffset=314-(314*v/100)}
function pct(v){return v==null||Number.isNaN(Number(v))?'—':`${Math.round(Number(v)*100)}%`}
function renderError(message){$('reading-title').textContent='We couldn\u2019t complete this reading.';$('reading-subtitle').textContent=message||'The backend could not be reached. No results are shown because THE THREE MAPS never displays invented map data.';$('num-value').textContent='Unavailable';$('num-copy').textContent='No result';$('astro-value').textContent='Unavailable';$('astro-copy').textContent='No result';$('astro-badge').textContent='UNAVAILABLE';$('palm-value').textContent='Awaiting image';$('palm-badge').textContent='NOT PROVIDED';$('relationship-state').textContent='Unavailable';$('relationship-copy').textContent='The reading could not be completed, so no relationship evaluation is available.';setFusion(null,'NOT CALCULATED');$('confidence').textContent=pct(null);$('coverage').textContent=pct(null);$('maps-count').textContent=`0 / ${state.maps.length}`;$('explanation-title').textContent='No result available';$('explanation-copy').textContent='THE THREE MAPS only shows results calculated by the V1 intelligence engine. Try again once the backend is reachable.';$('timing-note').textContent='TIMING: UNAVAILABLE';$('confidence-note').textContent='DATA CONFIDENCE: \u2014';}
$('lineage-btn').onclick=async()=>{const id=state.analysis?.analysis_id;if(!id){$('lineage').textContent='Audit trail is available when the live API is connected.';$('lineage').hidden=false;return}try{$('lineage').textContent=JSON.stringify(await fetch(`/v1/analyses/${id}/lineage`,{headers:{'Authorization':`Bearer ${API_TOKEN}`}}).then(r=>r.json()),null,2);$('lineage').hidden=false}catch(e){$('lineage').textContent=e.message;$('lineage').hidden=false}};
